# Chart Testing Configuration
# Used by ct lint and ct install commands

remote: origin
target-branch: main
chart-dirs:
  - infrastructure/helm
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - elastic=https://helm.elastic.co
  - minio=https://charts.min.io/
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - grafana=https://grafana.github.io/helm-charts
  - jaegertracing=https://jaegertracing.github.io/helm-charts
  - open-telemetry=https://open-telemetry.github.io/opentelemetry-helm-charts
helm-extra-args: --timeout 600s
validate-maintainers: false
check-version-increment: false
